### ISSUE TITLE
trying to get the basic install to work

### ISSUE THREAD

**Issue by neovich** [MattIPv4/PyDMXControl#28]
after typing initial install, first of list of errors appears.
file usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connection.py,
line 138 in _new_conn
??

**Comment by MattIPv4** [comment]
@neovich Do you have the full stack trace error and exactly what you were doing when it occurred (command or Python script)?

**Comment by neovich** [comment]
Hi There ,

Simply typed from command prompt . fresh raspbian install raspberry pi 3 b+
@ command line. (note : No libraries or dependancies loaded )

Simply typed at command prompt:
pip install -U PyDMXControl

get following errors:
-----------------------------------------------------------------------------------------------------------------------------------------------------------------
Exception:
Traceback (most recent call last):
  File
"/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connection.py",
line 138, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File
"/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/util/connection.py",
line 75, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 733, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -5] No address associated with hostname
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File
"/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py",
line 594, in urlopen
    chunked=chunked)
  File
"/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py",
line 350, in _make_request
    self._validate_conn(conn)
  File
"/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py",
line 837, in _validate_conn
    conn.connect()
  File
"/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connection.py",
line 281, in connect
    conn = self._new_conn()
  File
"/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connection.py",
line 147, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError:
<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at
0x74c46ef0>: Failed to establish a new connection: [Errno -5] No address
associated with hostname
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in
main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 353,
in run
    wb.build(autobuilding=True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in
prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 554, in
_prepare_file
    require_hashes
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 278,
in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 465, in
find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 423, in
find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python3/dist-packages/pip/index.py", line 568, in
_get_pages
    page = self._get_page(location)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 792, in get_page
    "Cache-Control": "max-age=600",
  File
"/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py",
line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/pip/download.py", line 386, in
request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File
"/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py",
line 488, in request
    resp = self.send(prep, **send_kwargs)
  File
"/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py",
line 630, in send
    history = [resp for resp in gen] if allow_redirects else []
  File
"/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py",
line 630, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File
"/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py",
line 190, in resolve_redirects
    **adapter_kwargs
  File
"/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py",
line 609, in send
    r = adapter.send(request, **kwargs)
  File
"/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py",
line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File
"/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/adapters.py",
line 423, in send
    timeout=timeout
  File
"/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py",
line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File
"/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/util/retry.py",
line 315, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'

-----------------------------------------------------------------------------------------------------------------------------------------------------------------
Am I missing something that is not so obvious to me ??

Cheers

**Comment by MattIPv4** [comment]
@neovich I suggest trying `python -m pip install - PyDMXControl`, I believe that raspbian uses python 2 by default (I might be wrong for newer releases).

**Comment by neovich** [comment]
Hi Again,
Raspbian does seem to have both versions of python but defaults to 2.7
Even if i do switch between python version (2.7 to 3.5 ) does not seem to
help.
tried your suggestion. ( 1 vary though )
python -m pip install - PyDMXControl ( typo ?? )
&
python -m pip install PyDMXControl
python3 -m pip install PyDMXControl

Errors:
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
Exception:
Traceback (most recent call last):
  File
"/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connection.py",
line 138, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File
"/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/util/connection.py",
line 75, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 733, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -5] No address associated with hostname
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File
"/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py",
line 594, in urlopen
    chunked=chunked)
  File
"/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py",
line 350, in _make_request
    self._validate_conn(conn)
  File
"/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py",
line 837, in _validate_conn
    conn.connect()
  File
"/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connection.py",
line 281, in connect
    conn = self._new_conn()
  File
"/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connection.py",
line 147, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError:
<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at
0x74bb7a70>: Failed to establish a new connection: [Errno -5] No address
associated with hostname
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in
main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 353,
in run
    wb.build(autobuilding=True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in
prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 554, in
_prepare_file
    require_hashes
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 278,
in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 465, in
find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 423, in
find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python3/dist-packages/pip/index.py", line 568, in
_get_pages
    page = self._get_page(location)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 792, in get_page
    "Cache-Control": "max-age=600",
  File
"/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py",
line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/pip/download.py", line 386, in
request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File
"/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py",
line 488, in request
    resp = self.send(prep, **send_kwargs)
  File
"/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py",
line 630, in send
    history = [resp for resp in gen] if allow_redirects else []
  File
"/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py",
line 630, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File
"/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py",
line 190, in resolve_redirects
    **adapter_kwargs
  File
"/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py",
line 609, in send
    r = adapter.send(request, **kwargs)
  File
"/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py",
line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File
"/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/adapters.py",
line 423, in send
    timeout=timeout
  File
"/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py",
line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File
"/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/util/retry.py",
line 315, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
Sorry to be a pain  ;-O
Out of all the python libraries I want to get going , this is number one
for me ;-)
I have loaded other python libraries on similar SD image OS (not on this OS
card )

neovich

**Comment by MattIPv4** [comment]
@neovich Hey, yeah, that was a typo, it should've been `python3 -m pip install PyDMXControl` which it looks like you tried.

This does very much appear to be an issue with the Python installation or pip, have you tried installing any other library with pip on this device yet?

**Comment by neovich** [comment]
Ah good point. Although I know the pip install has worked many a times on
my previous raspbian images (other SD cards ) , I Will try that on this
particular one.
Cheers

**Comment by neovich** [comment]
Hi,
No luck. It's ok. I am loading other modules with pip so it works 100 % .
I found another DMX module that works.that suits my requirement anyhow.
Thank you kindly for trying anyway

**Comment by neovich** [comment]
Hi,
Just a side note,

I tried:

PyDMXcontrol ,  rather than
PyDMXControl

(lower case c ) which got me almost where I needed to be.(less errors)
It got to the point where it was requiring python 3.6 install where
the current raspbian version only supports 3.5 for now. I did try
loading 3.6 but in the end, it messed my OS, lol, broke other scripts,
 so I stopped and reformatted.
( Yes, the env solution for using multi versions of python might be my answer )
Cheers

**Comment by MattIPv4** [comment]
Ah yes, you'll need 3.6 for this library. Sorry I couldn't help you further, the failure you're seeing is definitely occurring before the library itself is involved, so there is little I can do. Glad you found something else that is working :)

**Comment by neovich** [comment]
Hi,
Just to see, I am currently setting up python 3.7  on OS on my Pi.
Will still give your module a try , just to see if i can get it
working anyway.
Cheers
