### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by SirDagen** [MattIPv4/PyDMXControl#33]
Hi 

I am trying to install it on a Raspberry 3B+ and get the folllowing errors. Is it something I do wrong or is there an error in the script?

# ---

pi@zraspi:~ $ pip install PyDMXControl
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting PyDMXControl
  Could not find a version that satisfies the requirement PyDMXControl (from versions: )
No matching distribution found for PyDMXControl

# ---

pi@zraspi:~ $ pip install -U git+https://github.com/MattIPv4/PyDMXControl#egg=PyDMXControl[audio]
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting PyDMXControl[audio] from git+https://github.com/MattIPv4/PyDMXControl#egg=PyDMXControl[audio]
  Cloning https://github.com/MattIPv4/PyDMXControl to /tmp/pip-install-a3zRZy/PyDMXControl
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-a3zRZy/PyDMXControl/setup.py", line 27
        def fetch_reqs(base: str = "") -> List[str]:
                           ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-a3zRZy/PyDMXControl/

**Comment by MattIPv4** [comment]
This requires Python 3.6+, the fact it's raising a syntax error on a typehinted function would indicate you're using an older version of Python that doesn't support typehinting.

**Comment by SirDagen** [comment]
Hi Matt. Thanks I figured it out. Using the command...

pip3 install -U PyDMXControl[audio]

did the trick.

**Comment by MattIPv4** [comment]
Ah sweet, sounds like `pip` was using whatever Python 2 version Raspbian ships with. Nice to know that Raspbian now ships with 3.6+ as the default 3.x version :)
