### ISSUE TITLE
Cannot import 'OpenDMXController'

### ISSUE THREAD

**Issue by Schaggo** [MattIPv4/PyDMXControl#38]
Hi, 

I am trying to get started with DMX via python. After installing the package I seem to be missing some files. 

using `from PyDMXControl.controllers import OpenDMXController` exits with 
`ImportError: cannot import name 'OpenDMXController' from 'PyDMXControl.controllers' (/home/pi/startup/env/lib/python3.9/site-packages/PyDMXControl/controllers/__init__.py)`

Do I have to install the package in a specific location?

**Comment by Schaggo** [comment]
I just replaced all the files in the local site-package location with the files in the repo and it seems to work.

**Comment by MattIPv4** [comment]
Hey! Looks like you got this solved, but just wanted to note that the OpenDMX controller is not yet released on PyPi, so you'll want to follow the instructions in the README to install from this repo if you're looking to use it before I publish the 3.0.0 release (no ETA currently).

**Comment by Schaggo** [comment]
I did install it as described in the Readme. 
Stuff seems to be working - packets are being sent, lights turn on and off. 
Thanks again!
