### ISSUE TITLE
pip install not working?

### ISSUE THREAD

**Issue by static75** [MattIPv4/PyDMXControl#39]
pip install -U PyDMXControl
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting PyDMXControl
  Could not find a version that satisfies the requirement PyDMXControl (from versions: )
No matching distribution found for PyDMXControl

**Comment by MattIPv4** [comment]
🤔 The package is definitely available on PyPI: https://pypi.org/project/PyDMXControl/

**Comment by MattIPv4** [comment]
What version of Python and Pip are you using here?

**Comment by static75** [comment]
Python 3.7.3 (Thonny),  2.7.16 (command line),  pip 18.1

**Comment by MattIPv4** [comment]
How are you invoking pip? Could it be that the pip you're invoking is for the Python 2 install? Maybe try `python3 -m pip install -U PyDMXControl`?

**Comment by static75** [comment]
I got it to install using pip3 instead!
Next issue:  I get "No usb device opened" error when it tries to run dmx =
uDMXController()

**Comment by MattIPv4** [comment]
Hm, that'd suggest that the uDMX device (assuming you've got one connected) isn't being detected by PyUSB. Do you have the correct drivers installed for the uDMX device you have?

**Comment by static75** [comment]
I have a USB-to-DMX cable attached to the RPI.  I know the cable works
because I tested it with my windows laptop and Freestyler to connect to my
ADJ light fixture to control pan, tilt, dimmer, etc.
I'm now trying to control the same ADJ light fixture with the same cable
from the USB port of the RPI.  I'm probably missing a very simple step to
make it work.

**Comment by MattIPv4** [comment]
Closing out as the original issue this was created for was resolved, and I'm not sure I can provide much help on driver-specific issues with devices.
