### ISSUE TITLE
All 512 channels being sent every transmission causes slow down.

### ISSUE THREAD

**Issue by Joe-Speers** [MattIPv4/PyDMXControl#41]
Thank you for this very helpful library!
I came across an issue with my uDMX device when trying to fade colours, the transition was very jerky. I found that `uDMXController._transmit()` was only sending data at about 6 times per second, this seems surprisingly slow.

I was able to speed this up significantly (to about 30Hz) by changing:
`self.__udmx.send_multi_value(first, frame)`
to
`self.__udmx.send_multi_value(first, frame[0:8])`
As far as I understand, `frame` contains all 512 channels and these are all sent every update, causing a significant delay. Instead sending only 8 channels massively sped up the response.

I was wondering if there is some way to reduce the size of `frame` depending on the number of fixtures the user needs, or only transmit the channels that have changed since the last transmission?

**Comment by MattIPv4** [comment]
Hey! You can set `dynamic_frame` when you creat the controller, which will do essentially what you were doing manually (truncate the frame data to the active fixtures):

https://github.com/MattIPv4/PyDMXControl/blob/c955a196c0c5091c2a5b070f3ab6b887e5cdfbc4/PyDMXControl/controllers/_Controller.py#L54

https://github.com/MattIPv4/PyDMXControl/blob/c955a196c0c5091c2a5b070f3ab6b887e5cdfbc4/PyDMXControl/controllers/_Controller.py#L186-L188

https://github.com/MattIPv4/PyDMXControl/blob/c955a196c0c5091c2a5b070f3ab6b887e5cdfbc4/PyDMXControl/controllers/_TransmittingController.py#L62-L66

**Comment by Joe-Speers** [comment]
That's brilliant, thank you!
