### ISSUE TITLE
No backend available

### ISSUE THREAD

**Issue by PrincesseLulu** [MattIPv4/PyDMXControl#42]
Hello, just install from pip with python 3.11.1 and i got an error when i try to use PyDMXController.

![image](https://user-images.githubusercontent.com/18584249/209209113-cd1ee221-5f14-4f75-b3f9-f5d9fac8ac50.png)

Can you help me ? I wan't use this lib for a xmas project, i'm afraid about time if I keep blocked.

Thanks by advance for your help !

**Comment by MattIPv4** [comment]
👋 Do you have an OpenDMX-compatible USB device connected?

**Comment by MattIPv4** [comment]
You may want to pass `ftdi_vendor_id` and/or `ftdi_product_id` and/or `ftdi_serial` with specific values for you device to help locate it. The code defaults to `0x0403` for the vendor id and `0x6001` for the product id:

https://github.com/MattIPv4/PyDMXControl/blob/c955a196c0c5091c2a5b070f3ab6b887e5cdfbc4/PyDMXControl/controllers/_OpenDMXController.py#L17-L21

https://github.com/MattIPv4/PyDMXControl/blob/c955a196c0c5091c2a5b070f3ab6b887e5cdfbc4/PyDMXControl/controllers/_OpenDMXController.py#L38-L39

**Comment by PrincesseLulu** [comment]
This is not better, but with de short time that I got I finnaly use a c# library. Thanks for your help.

**Comment by mbalasso** [comment]
Hi there, 
I had the same issue with Enttec OpenDMX USB on macOs, fixed by setting the LD_LIBRARY_PATH as mentioned here https://eblot.github.io/pyftdi/troubleshooting.html#error-no-backend-available

Cheers
