### ISSUE TITLE
"ValueError: 'name' may not be empty." when Flask 2.3.x installed

### ISSUE THREAD

**Issue by forceflow1049** [MattIPv4/PyDMXControl#45]
Flask appears to have made a change in the 2.3.x series that the name of a `Blueprint` cannot be the empty string.

For example, with Flask 2.3.2 installed, importing

```
from PyDMXControl.controllers import OpenDMXController
```

results in the exception:

```
File "C:\Users\ASC\Documents\constellation-dev\build\apps\venv_3_11\Lib\site-packages\PyDMXControl\web\_routes.py", line 17, in <module>
    routes = Blueprint('', __name__, url_prefix='/')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASC\Documents\constellation-dev\build\apps\venv_3_11\Lib\site-packages\flask\blueprints.py", line 196, in __init__
    raise ValueError("'name' may not be empty.")
ValueError: 'name' may not be empty.
```

I have verified this in Windows and macOS. Forcing the install of Flask 2.2.4 resolves this problem. The fix should be as easy as replacing '' with any value.

**Comment by pauljurczak** [comment]
The same (obviously) on Ubuntu 22.04.2 with Python 3.11.3. 
```
pip install --force-reinstall flask==2.2.4
```
Fixes it.

**Comment by ZotAlan** [comment]
This worked for me.  Thanks.

**Comment by MattIPv4** [comment]
#53
