### ISSUE TITLE
Using `ftdi_vendor_id`/`ftdi_product_id` in `OpenDMXController`?

### ISSUE THREAD

**Issue by ZotAlan** [MattIPv4/PyDMXControl#48]
You might want to pass `ftdi_vendor_id` and/or `ftdi_product_id` as keyword args into `OpenDMXController` based on the device you are using, if the defaults aren't correct?

https://github.com/MattIPv4/PyDMXControl/blob/27d41b33689eb197492a5928494a6d2f15ac391e/PyDMXControl/controllers/_OpenDMXController.py#L19-L21

_Originally posted by @MattIPv4 in https://github.com/MattIPv4/PyDMXControl/issues/47#issuecomment-1572537170_

**Comment by ZotAlan** [comment]
I'm still stuck on no backend available.  For troubleshooting I wanted to use your above code snips but it's beyond my Python experience to know where to place.

**Comment by ZotAlan** [comment]
I was hoping to hear something.  For what it is worth, I don't think the issue (no backend available) is with PyDMX.  I think it's a WinUSB or LibUSB driver issue.

**Comment by MattIPv4** [comment]
Apologies for not responding sooner, I didn't realise you'd pulled that comment out into a new issue...

They are standard Python keyword arguments, so `OpenDMXController(ftdi_vendor_id = "whatever", ftdi_product_id = "whatever")`

I would agree with your assessment though, based on what other folks have reported, that this is mostly likely a driver issue.

**Comment by MattIPv4** [comment]
Closing out as an answer has been given for the issue raised.
